### ISSUE TITLE
Build Script Fails on Zeit Now

### ISSUE THREAD

**Issue by rbutera** [fabe/gatsby-universal#64]
## Description
For some reason I can develop/build locally but not if I try to deploy a gatsby-universal project using zeit now.

## Logs

```
2020-01-23T17:53:01.390Z  [Favicons] Image:create: Creating empty 2688x1242 canvas with #fff background...
2020-01-23T17:53:01.417Z  [Favicons] Image:render: Find nearest icon to 2688x1242 with offset 0...
2020-01-23T17:53:01.417Z  [Favicons] Images:render: Resizing PNG to 2688x1242...
2020-01-23T17:53:01.436Z  [Favicons] Image:create: Creating empty 2048x1536 canvas with #fff background...
2020-01-23T17:53:01.459Z  [Favicons] Image:render: Find nearest icon to 2048x1536 with offset 0...
2020-01-23T17:53:01.459Z  [Favicons] Images:render: Resizing PNG to 2048x1536...
2020-01-23T17:53:01.471Z  [Favicons] Image:create: Creating empty 2224x1668 canvas with #fff background...
2020-01-23T17:53:01.499Z  [Favicons] Image:render: Find nearest icon to 2224x1668 with offset 0...
2020-01-23T17:53:01.499Z  [Favicons] Images:render: Resizing PNG to 2224x1668...
2020-01-23T17:53:01.511Z  [Favicons] Image:create: Creating empty 2388x1668 canvas with #fff background...
2020-01-23T17:53:01.541Z  [Favicons] Image:render: Find nearest icon to 2388x1668 with offset 0...
2020-01-23T17:53:01.541Z  [Favicons] Images:render: Resizing PNG to 2388x1668...
2020-01-23T17:53:01.554Z  [Favicons] Image:create: Creating empty 2732x2048 canvas with #fff background...
2020-01-23T17:53:01.598Z  [Favicons] Image:render: Find nearest icon to 2732x2048 with offset 0...
2020-01-23T17:53:01.598Z  [Favicons] Images:render: Resizing PNG to 2732x2048...
2020-01-23T17:53:01.734Z  [Favicons] Images:composite: Compositing favicon on 640x1136 canvas with offset 0...
2020-01-23T17:53:02.058Z  [Favicons] Images:composite: Compositing favicon on 750x1334 canvas with offset 0...
2020-01-23T17:53:02.505Z  [Favicons] Images:composite: Compositing favicon on 828x1792 canvas with offset 0...
2020-01-23T17:53:03.192Z  [Favicons] Images:composite: Compositing favicon on 1125x2436 canvas with offset 0...
2020-01-23T17:53:04.260Z  [Favicons] Images:composite: Compositing favicon on 1242x2208 canvas with offset 0...
2020-01-23T17:53:05.296Z  [Favicons] Images:composite: Compositing favicon on 1242x2688 canvas with offset 0...
2020-01-23T17:53:06.569Z  [Favicons] Images:composite: Compositing favicon on 1536x2048 canvas with offset 0...
2020-01-23T17:53:07.859Z  [Favicons] Images:composite: Compositing favicon on 1668x2224 canvas with offset 0...
2020-01-23T17:53:09.328Z  [Favicons] Images:composite: Compositing favicon on 1668x2388 canvas with offset 0...
2020-01-23T17:53:11.057Z  [Favicons] Images:composite: Compositing favicon on 2048x2732 canvas with offset 0...
2020-01-23T17:53:12.619Z  [Favicons] Images:composite: Compositing favicon on 1136x640 canvas with offset 0...
2020-01-23T17:53:13.244Z  [Favicons] Images:composite: Compositing favicon on 2160x1620 canvas with offset 0...
2020-01-23T17:53:14.602Z  [Favicons] Images:composite: Compositing favicon on 1620x2160 canvas with offset 0...
2020-01-23T17:53:15.701Z  [Favicons] Images:composite: Compositing favicon on 1334x750 canvas with offset 0...
2020-01-23T17:53:16.131Z  [Favicons] Images:composite: Compositing favicon on 1792x828 canvas with offset 0...
2020-01-23T17:53:16.809Z  [Favicons] Images:composite: Compositing favicon on 2436x1125 canvas with offset 0...
2020-01-23T17:53:17.805Z  [Favicons] Images:composite: Compositing favicon on 2208x1242 canvas with offset 0...
2020-01-23T17:53:18.906Z  [Favicons] Images:composite: Compositing favicon on 2688x1242 canvas with offset 0...
2020-01-23T17:53:20.176Z  [Favicons] Images:composite: Compositing favicon on 2048x1536 canvas with offset 0...
2020-01-23T17:53:21.461Z  [Favicons] Images:composite: Compositing favicon on 2224x1668 canvas with offset 0...
2020-01-23T17:53:22.896Z  [Favicons] Images:composite: Compositing favicon on 2388x1668 canvas with offset 0...
2020-01-23T17:53:24.652Z  [Favicons] Images:composite: Compositing favicon on 2732x2048 canvas with offset 0...
2020-01-23T17:53:26.121Z  [Favicons] Image:create: Creating empty 70x70 canvas with transparent background...
2020-01-23T17:53:26.122Z  [Favicons] Image:render: Find nearest icon to 70x70 with offset 0...
2020-01-23T17:53:26.122Z  [Favicons] Images:render: Resizing PNG to 70x70...
2020-01-23T17:53:26.137Z  [Favicons] Image:create: Creating empty 144x144 canvas with transparent background...
2020-01-23T17:53:26.137Z  [Favicons] Image:render: Find nearest icon to 144x144 with offset 0...
2020-01-23T17:53:26.137Z  [Favicons] Images:render: Resizing PNG to 144x144...
2020-01-23T17:53:26.150Z  [Favicons] Image:create: Creating empty 150x150 canvas with transparent background...
2020-01-23T17:53:26.150Z  [Favicons] Image:render: Find nearest icon to 150x150 with offset 0...
2020-01-23T17:53:26.150Z  [Favicons] Images:render: Resizing PNG to 150x150...
2020-01-23T17:53:26.162Z  [Favicons] Image:create: Creating empty 310x150 canvas with transparent background...
2020-01-23T17:53:26.163Z  [Favicons] Image:render: Find nearest icon to 310x150 with offset 0...
2020-01-23T17:53:26.163Z  [Favicons] Images:render: Resizing PNG to 310x150...
2020-01-23T17:53:26.175Z  [Favicons] Image:create: Creating empty 310x310 canvas with transparent background...
2020-01-23T17:53:26.175Z  [Favicons] Image:render: Find nearest icon to 310x310 with offset 0...
2020-01-23T17:53:26.176Z  [Favicons] Images:render: Resizing PNG to 310x310...
2020-01-23T17:53:26.188Z  [Favicons] Files:create: Creating file: browserconfig.xml...
2020-01-23T17:53:26.215Z  [Favicons] Images:composite: Compositing favicon on 70x70 canvas with offset 0...
2020-01-23T17:53:26.245Z  [Favicons] Images:composite: Compositing favicon on 144x144 canvas with offset 0...
2020-01-23T17:53:26.272Z  [Favicons] Images:composite: Compositing favicon on 150x150 canvas with offset 0...
2020-01-23T17:53:26.306Z  [Favicons] Images:composite: Compositing favicon on 310x150 canvas with offset 0...
2020-01-23T17:53:26.359Z  [Favicons] Images:composite: Compositing favicon on 310x310 canvas with offset 0...
2020-01-23T17:53:26.469Z  internal/modules/cjs/loader.js:800
2020-01-23T17:53:26.469Z      throw err;
2020-01-23T17:53:26.469Z      ^
2020-01-23T17:53:26.469Z  
2020-01-23T17:53:26.469Z  Error: Cannot find module 'core-js/modules/es7.array.flat-map'
2020-01-23T17:53:26.469Z  Require stack:
2020-01-23T17:53:26.469Z  - /zeit/228ed835/node_modules/gatsby/node_modules/gatsby-cli/lib/index.js
2020-01-23T17:53:26.469Z  - /zeit/228ed835/node_modules/gatsby/dist/bin/gatsby.js
2020-01-23T17:53:26.469Z      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
2020-01-23T17:53:26.469Z      at Function.Module._load (internal/modules/cjs/loader.js:690:27)
2020-01-23T17:53:26.469Z      at Module.require (internal/modules/cjs/loader.js:852:19)
2020-01-23T17:53:26.469Z      at require (internal/modules/cjs/helpers.js:74:18)
2020-01-23T17:53:26.469Z      at Object.<anonymous> (/zeit/228ed835/node_modules/gatsby/node_modules/gatsby-cli/lib/index.js:6:1)
2020-01-23T17:53:26.469Z      at Module._compile (internal/modules/cjs/loader.js:959:30)
2020-01-23T17:53:26.469Z      at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2020-01-23T17:53:26.470Z      at Module.load (internal/modules/cjs/loader.js:815:32)
2020-01-23T17:53:26.470Z      at Function.Module._load (internal/modules/cjs/loader.js:727:14)
2020-01-23T17:53:26.470Z      at Module.require (internal/modules/cjs/loader.js:852:19) {
2020-01-23T17:53:26.470Z    code: 'MODULE_NOT_FOUND',
2020-01-23T17:53:26.470Z    requireStack: [
2020-01-23T17:53:26.470Z      '/zeit/228ed835/node_modules/gatsby/node_modules/gatsby-cli/lib/index.js',
2020-01-23T17:53:26.470Z      '/zeit/228ed835/node_modules/gatsby/dist/bin/gatsby.js'
2020-01-23T17:53:26.470Z    ]
2020-01-23T17:53:26.470Z  }
2020-01-23T17:53:26.472Z  npm ERR! code ELIFECYCLE
2020-01-23T17:53:26.472Z  npm ERR! errno 1
2020-01-23T17:53:26.473Z  npm ERR! gatsby-universal@ build: `npm run build:dir && npm run build:favicons && gatsby build`
2020-01-23T17:53:26.473Z  npm ERR! Exit status 1
2020-01-23T17:53:26.473Z  npm ERR! 
2020-01-23T17:53:26.473Z  npm ERR! Failed at the gatsby-universal@ build script.
2020-01-23T17:53:26.473Z  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-01-23T17:53:26.478Z  
2020-01-23T17:53:26.478Z  npm ERR! A complete log of this run can be found in:
2020-01-23T17:53:26.478Z  npm ERR!     /zeit/.npm/_logs/2020-01-23T17_53_26_473Z-debug.log
2020-01-23T17:53:26.484Z  Error: Exited with 1
2020-01-23T17:53:26.485Z      at ChildProcess.child.on (/zeit/7783010c87aa68f0/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:31880:24)
2020-01-23T17:53:26.485Z      at emitTwo (events.js:126:13)
2020-01-23T17:53:26.485Z      at ChildProcess.emit (events.js:214:7)
2020-01-23T17:53:26.485Z      at maybeClose (internal/child_process.js:925:16)
2020-01-23T17:53:26.485Z      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2020-01-23T17:53:26.596Z  worker exited with code 20 and signal null
2020-01-23T17:53:28.999Z  done

```

## Thoughts
I think the important line is `Cannot find module 'core-js/modules/es7.array.flat-map'`

Is this a babel issue?

**Comment by whyboris** [comment]
Unsure what's happening, but I have 2 websites based off this repository in _Zeit_ (now **Vercel**) and they both work:
- https://github.com/whyboris/yboris.dev
- https://github.com/whyboris/yboris.com

Is the issue still happening for you?

**Comment by whyboris** [comment]
✅ 2023 update -- still works 😎 -- even after updating to _Gatsby 5_ 🚀
